# Generated by Django 4.1.7 on 2023-02-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='', verbose_name='upload_to=profile_pic/'),
            preserve_default=False,
        ),
    ]
