# Generated by Django 4.1.7 on 2023-02-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profile_image',
            new_name='product_image',
        ),
    ]
